//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiChrysallis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chrysallisEntities : DbContext
    {
        public chrysallisEntities()
            : base("name=chrysallisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comunitats> comunitats { get; set; }
        public virtual DbSet<documents> documents { get; set; }
        public virtual DbSet<esdeveniments> esdeveniments { get; set; }
        public virtual DbSet<rols> rols { get; set; }
        public virtual DbSet<socis> socis { get; set; }
        public virtual DbSet<usuaris> usuaris { get; set; }
        public virtual DbSet<valoracions> valoracions { get; set; }
    }
}
